[package]
name = "include-compress-bytes"
version = "0.1.0"
edition = "2024"

[features]
default = ["brotli"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
sha2 = "0.10.9"
brotli = { version = "8.0.2", optional = true }

[dev-dependencies]
trybuild = "1.0.103"

[build-dependencies]
cargo-emit = "0.2.1"
